language: node_js

node_js:
  - "10"
cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm install -g codecov

env:
  global:
  - NODE_ENV=test

script:
  - npm run test:remote
  - nyc report --reporter=text-lcov > coverage.lcov && codecov


